version: "3"
services:
  rucioclient:
    image: docker.io/rucio/rucio-dev:py3
    command: ["sleep", "10000"]
    volumes:
      - ../../../tools:/opt/rucio/tools:Z
      - ../../../bin:/opt/rucio/bin:Z
      - ../../../lib:/opt/rucio/lib:Z
    environment:
      - X509_USER_CERT=/opt/rucio/etc/usercert.pem
      - X509_USER_KEY=/opt/rucio/etc/userkey.pem
  rucio:
    image: docker.io/rucio/rucio-dev:py3
    volumes:
      - ../../../tools:/opt/rucio/tools:Z
      - ../../../bin:/opt/rucio/bin:Z
      - ../../../lib:/opt/rucio/lib:Z
    environment:
      - X509_USER_CERT=/opt/rucio/etc/usercert.pem
      - X509_USER_KEY=/opt/rucio/etc/userkey.pem
      - RDBMS=postgres11
  ruciodb:
    image: docker.io/postgres:11
    environment:
      - POSTGRES_USER=rucio
      - POSTGRES_DB=rucio
      - POSTGRES_PASSWORD=secret
    command: ["-c", "fsync=off","-c", "synchronous_commit=off","-c", "full_page_writes=off"]
  graphite:
    image: docker.io/graphiteapp/graphite-statsd
  fts:
    image: docker.io/rucio/fts
  ftsdb:
    image: docker.io/mysql:5
    environment:
      - MYSQL_USER=fts
      - MYSQL_PASSWORD=fts
      - MYSQL_ROOT_PASSWORD=fts
      - MYSQL_DATABASE=fts
  xrd1:
    image: docker.io/rucio/xrootd
    environment:
      - XRDPORT=1094
    volumes:
      - ../../certs/hostcert_xrd1.pem:/tmp/xrdcert.pem:Z
      - ../../certs/hostcert_xrd1.key.pem:/tmp/xrdkey.pem:Z
  xrd2:
    image: docker.io/rucio/xrootd
    environment:
      - XRDPORT=1095
    volumes:
      - ../../certs/hostcert_xrd2.pem:/tmp/xrdcert.pem:Z
      - ../../certs/hostcert_xrd2.key.pem:/tmp/xrdkey.pem:Z
  xrd3:
    image: docker.io/rucio/xrootd
    environment:
      - XRDPORT=1096
    volumes:
      - ../../certs/hostcert_xrd3.pem:/tmp/xrdcert.pem:Z
      - ../../certs/hostcert_xrd3.key.pem:/tmp/xrdkey.pem:Z
  xrd4:
    image: docker.io/rucio/xrootd
    environment:
      - XRDPORT=1097
    volumes:
      - ../../certs/hostcert_xrd4.pem:/tmp/xrdcert.pem:Z
      - ../../certs/hostcert_xrd4.key.pem:/tmp/xrdkey.pem:Z
  minio:
    image: docker.io/minio/minio
    environment:
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password
    volumes:
      - ../../certs/hostcert_minio.pem:/root/.minio/certs/public.crt:Z
      - ../../certs/hostcert_minio.key.pem:/root/.minio/certs/private.key:Z
    command: ["server", "/data"]
